RUB:
  symbol: ₽
  fullname: ruble
  plural_name: rubles
  short_name: rub.

USD:
  symbol: $
  fullname: dollar
  plural_name: dollars
  short_name: US$

EUR:
  symbol: €
  fullname: auro
  plural_name: euros
  short_name: euro

GBP:
  symbol: "£"
  fullname: "pound sterling"
  plural_name: pounds
  short_name: pound

CNY:
  symbol: "¥"
  fullname: chinese yuan
  plural_name: yuan
  short_name: yuan
